import type { CodegenPlugin } from "@graphql-codegen/plugin-helpers";

const plugin: CodegenPlugin = {
  plugin() {
    return "// Generated by graphql-codegen-registry\n\n";
  },
};

export default plugin;
