import type { PluginFunction } from "@graphql-codegen/plugin-helpers";
import { capitalize } from "es-toolkit/string";
import { Kind, type OperationDefinitionNode } from "graphql";

type OpKind = "query" | "mutation" | "subscription";

type OperationMeta = {
  name: string;
  kind: OpKind;
  variablesType: string;
  resultType: string;
  documentConst: string;
};

export const plugin: PluginFunction = (_schema, documents) => {
  const ops: OperationMeta[] = [];

  for (const doc of documents) {
    if (!doc.document) continue;

    for (const def of doc.document.definitions) {
      if (def.kind !== Kind.OPERATION_DEFINITION) continue;

      const op = def as OperationDefinitionNode;
      if (!op.name?.value) continue;

      const name = op.name.value;
      const kind = op.operation as OpKind;
      const suffix = capitalize(kind) as "Query" | "Mutation" | "Subscription";

      ops.push({
        name,
        kind,
        variablesType: `${name}${suffix}Variables`,
        resultType: `${name}${suffix}Result`,
        documentConst: `${name}Document`,
      });
    }
  }

  const uniqueOps = Array.from(new Map(ops.map((o) => [o.name, o])).values());

  const registryEntries = uniqueOps
    .map(
      (op) => `  ${op.name}: OperationEntry<${op.variablesType}, ${op.resultType}, "${op.kind}">;`,
    )
    .join("\n");

  const registryValues = uniqueOps
    .map((op) => `  ${op.name}: { kind: "${op.kind}", document: ${op.documentConst} },`)
    .join("\n");

  return `
// Generated by graphql-codegen-registry
import type { DocumentNode } from "graphql";

export interface OperationEntry<TVariables, TResult, TKind extends "query" | "mutation" | "subscription"> {
  kind: TKind;
  variables: TVariables;
  result: TResult;
  document: DocumentNode;
}

export type OperationRegistry = {
${registryEntries}
};

export type OperationName = keyof OperationRegistry;
export type QueryName = { [K in keyof OperationRegistry]: OperationRegistry[K]["kind"] extends "query" ? K : never }[keyof OperationRegistry];
export type MutationName = { [K in keyof OperationRegistry]: OperationRegistry[K]["kind"] extends "mutation" ? K : never }[keyof OperationRegistry];
export type SubscriptionName = { [K in keyof OperationRegistry]: OperationRegistry[K]["kind"] extends "subscription" ? K : never }[keyof OperationRegistry];

export type VariablesOf<TName extends keyof OperationRegistry> = OperationRegistry[TName]["variables"];
export type ResultOf<TName extends keyof OperationRegistry> = OperationRegistry[TName]["result"];

export const registry: { [K in keyof OperationRegistry]: { kind: OperationRegistry[K]["kind"]; document: DocumentNode } } = {
${registryValues}
};
`;
};

export default { plugin };
